name: geo_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - imageio
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - xarray
  - tqdm
  - cartopy
  - shapely<2.0
  - netcdf4
  - pydap
  - cfgrib
  - eccodes
  - gdal
  - fiona
  - pyogrio
  - ffmpeg
  - dask
  - bottleneck
